#!/usr/bin/env zsh

repo_name=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)") || exit 1

git remote add forgejo "ssh://git@code.dadams.org/dadams/${repo_name}" 2>/dev/null
git push --all -u forgejo --follow-tags
