#!/bin/bash


# Some inspiration https://github.dev/dgrebb/dotfiles and https://github.dev/d12frosted/environment

# Global settings
yabai -m config \
    external_bar all:32:0 \
    window_placement second_child \
    window_zoom_persist on \
    window_shadow on \
    window_opacity off \
    insert_feedback_color 0xff9dd274 \
    mouse_follows_focus on \
    focus_follow_ouse autofocus \
    mouse_modifier alt \
    mouse_drop_action stack \

# Space settings
yabai -m config \
    layout bsp \
    split_type auto \
    top_padding 6 \
    bottom_padding 8 \
    left_padding 8 \
    right_padding 8 \
    auto_balance off \
    window_gap 6 \

# sensure we have the correct amount of spaces
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 9)'); do
  yabai -m space --destroy 10 
done

# exclusions
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Firefox" app="^Firefox$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app=Calculator manage=off

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


printf "\033[0;32m✓ Yabai configuration loaded!\033[0m\n\n"
